### ISSUE TITLE
SetErrors

### ISSUE THREAD

**Issue by SmartPhoneJava** [go-park-mail-ru/2020_1_TPRangers#14]
https://github.com/go-park-mail-ru/2020_1_TPRangers/blob/3ac132c6d0b29cd0c61d3b9b6fb0106041ad273d/server/main.go#L81-L84

- Не стоит превращать ошибки в строки. Однажды вам понадобится выяснить, где произошла ошибка. Для этого вы сможете воспользоваться трейсингом ошибок(например [tracerr](https://github.com/ztrue/tracerr)), он покажет стек вызовов до момента возникновения ошибки. Но это работает только с типом `error`, а у вас `string`. Так что либо создавайте ошибки на основе вашего пакета errors, либо храните там не строки, а `error`, как это делают в некоторых [стандартных](https://golang.org/pkg/path/filepath/#pkg-variables) библиотеках
- А для чего слайс строк, а не 1 строка?) В вызовах я вижу сплошные слайсы из одного элемента :smiley: 
https://github.com/go-park-mail-ru/2020_1_TPRangers/blob/3ac132c6d0b29cd0c61d3b9b6fb0106041ad273d/server/main.go#L134
https://github.com/go-park-mail-ru/2020_1_TPRangers/blob/3ac132c6d0b29cd0c61d3b9b6fb0106041ad273d/server/main.go#L102
- Вижу вы разыменовываете `*http.ResponseWriter`. Но... почему он вообще указатель? Разве это удобно каждый раз разадресовывать его, а потом разыменовывать? Просто принимайте на вход сам `http.ResponseWriter`, а не указатель

**Comment by SmartPhoneJava** [comment]
Те же вопросы и к `SetData`, для чего там аргументов функции является слайс строк, если вы кидаете всегда по одной строке... Ну и опять таки указатель на `http.ResponseWriter`

**Comment by znjuko** [comment]
Поправлю на ошибки) 


Просто я писал функции с расчётом на то, что в будущем понадобится выбрасывать сразу несколько ошибок на фронт,но что-то пошло не так
