### ISSUE TITLE
SettingsUpload

### ISSUE THREAD

**Issue by SmartPhoneJava** [go-park-mail-ru/2020_1_TPRangers#15]
https://github.com/go-park-mail-ru/2020_1_TPRangers/blob/3ac132c6d0b29cd0c61d3b9b6fb0106041ad273d/server/main.go#L303-L335

- Для чего цикл? Можно ведь просто последовательно написать все эти команды? Это немного необычно.
- `errGetFile != http.ErrMissingFile` Та функция точно не может вернуть другие ошибки? Может все таки стоит использовать дефолтное `errGetFile == nil`?

**Comment by znjuko** [comment]
я переписал эту функцию

а сделал цикл с switch-case ля того, чтобы 
-не писать много  if
- при изменении структуры JSON нам не нужно было сильно запариваться и переписывать всю логику, просто переписать ключевые слова в uploadDataFlags  и переделать switch
